version: '3.4'
services:
  letstrack-database:
    build: ./database
    image: xaivntaaj/letstrack-database:1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  letstrack-backend:
    build: ./backend
    image: xaivntaaj/letstrack-backend:1.0
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - "letstrack-database"
    command: >
      sh -c "flask db upgrade && gunicorn -b 0.0.0.0 app:app"

  letstrack-frontend:
    build: ./frontend
    image: xaivntaaj/letstrack-frontend:1.0
    ports:
      - 3000:3000
      - 80:80
      - 443-443
    depends_on:
      - "letstrack-backend"
volumes:
  db-data: