"""update

Revision ID: 0ea70397dfe7
Revises: e4e44507a101
Create Date: 2023-06-11 19:59:28.757647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ea70397dfe7'
down_revision = 'e4e44507a101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.drop_constraint('promotion_ibfk_4', type_='foreignkey')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('promotion_ibfk_4', 'user', ['coach_id'], ['id'])

    # ### end Alembic commands ###
