"""update

Revision ID: 2cfa370a6f9a
Revises: e7c086439666
Create Date: 2023-06-08 11:58:09.970917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfa370a6f9a'
down_revision = 'e7c086439666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('is_coach')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('is_coach', ['is_coach'], unique=False)

    # ### end Alembic commands ###
