"""update Event model

Revision ID: 9ed5ed7982ab
Revises: 18de66081ef8
Create Date: 2023-06-08 14:41:05.275827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ed5ed7982ab'
down_revision = '18de66081ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=False))
        batch_op.drop_column('is_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_class', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###
