"""udpate user model

Revision ID: b560b5e4db4d
Revises: 9ed5ed7982ab
Create Date: 2023-06-09 13:33:58.317121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b560b5e4db4d'
down_revision = '9ed5ed7982ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin', sa.String(length=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin')

    # ### end Alembic commands ###
