"""update

Revision ID: f2866c1d216d
Revises: fe1afaa34acb
Create Date: 2023-06-11 18:37:57.664034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2866c1d216d'
down_revision = 'fe1afaa34acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.drop_constraint('promotion_ibfk_1', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('promotion_ibfk_1', 'event', ['event_id'], ['id'])

    # ### end Alembic commands ###
