"""update

Revision ID: fe1afaa34acb
Revises: 626172d26ff8
Create Date: 2023-06-09 15:20:11.782613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe1afaa34acb'
down_revision = '626172d26ff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=mysql.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pin',
               existing_type=mysql.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###
